This is makeindex, version 2.15 [TeX Live 2009] (kpathsea + Thai support).
Scanning style file ./Master.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Master.acn....done (703 entries accepted, 0 rejected).
Sorting entries........done (7328 comparisons).
Generating output file Master.acr....done (393 lines written, 0 warnings).
Output written in Master.acr.
Transcript written in Master.alg.
